### PR TITLE
Generic map handling

### PR DESCRIPTION
**Pull request by EvaSDK**
Supersedes PR #32.

A rebased work to get rid of individual handling of lookup table files.

I wanted to merge aliases handling and proper multiple file support but I have been using this for months without issue so I guess it is better to share it now than whenever I get the time to add these features.

### CODE REVIEW

**Comment by aboe76** [comment]
@EvaSDK is this backwards compatible?

**Comment by EvaSDK** [comment]
No, you have to move the mappings from the current definition to a `mappings` key as can be seen in the diff on `pillar.example`. I could probably find a way to make it backward compatible but I am not aware of any way to say it is deprecated so users are encouraged to migrate to the new form. Also it is mostly a simple copy/paste.

**Comment by aboe76** [comment]
ok @EvaSDK I would like to merge this but I feel the need to ask others if they are ok with this change 
@gravyboat can you take a look?

**Comment by gravyboat** [comment]
I looked at this previously when it popped up and didn't comment because you guys were already discussing. It looks like a good change to me.

**Comment by aboe76** [comment]
@gravyboat and @EvaSDK then I will merge this hopefully everybody pays attention to the change in pillar.example

**Comment by EvaSDK** [comment]
Thanks.

**Pull request merged**
