### PR TITLE
test(default): add inspec for base and maps

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <fzipitria@perceptyx.com>

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [x] Updated the relevant test pillar.

### CODE REVIEW

**Comment by fzipi** [comment]
Ready to merge!

**Comment by myii** [comment]
@fzipi Looks really detailed -- kudos!

Where does the ` test/salt/pillar/postgrey.sls` pillar get used?  Does that need to be added to `kitchen.yml`?

**Comment by fzipi** [comment]
:thinking: two tests slipped: postgrey and mysql. I'm removing the mysql test (that does nothing yet), and will push those next.

**Comment by myii** [comment]
Nice work, @fzipi -- merged.

**Pull request merged**
