### PR TITLE
More pillar managed services

### PR DESCRIPTION
**Pull request by ixs**
Most of the services in master.cf were already configurable through
the formula but specific ones such as cyrus or uucp were not managed
yet.

This commit adds functionality to manage these services as well
through pillar variables, e.g.:

```
postfix:
  master_config:
    services:
      uucp:
	enable: True
```

Drive-By: Fix the use of the xbin_prefix variable for the spf daemon.

### CODE REVIEW

**Comment by ixs** [comment]
Additional note, this PR would close Issue #46 as maildrop is now managable from pillars.

**Comment by javierbertoli** [comment]
@ixs, I think I'm missing something here, but I fail to see why we need a whole new macro (`extra_service`) to manage these services, instead of using the previously defined one.

Doesn't just adding these services in the `services.jinja` file, with correct parameters, but `disabled` by default, cover the case more simply?

**Comment by ixs** [comment]
@javierbertoli The difference is that the code I previously committed to manage the master.cf file using the services dict works was designed for the postfix internal processes. e.g. all the subprocesses used by the postfix daemon.

The services configured by the extra_services macro are slightly different as in most of these are interfaces to external mailstores and use the pipe delivery daemon with varying number of extra parameters, something that does not well fit into the existing postfix-internal services framework.
_Especially_ if you want to keep any kind of semblance to the master.cf file as it is known to most people.

That being said, I think it might make sense to extend the code a little bit. Right now it is dealing very well with services that are defined in the master.cf like uucp, maildrop etc.
It does not deal well with adding completely new services that have not been defined before, like the dovecot service already if-def'ed in the main.cf file.

I'll push another iteration that will handle both the existing pipe services (maildrop, uucp, bsmtp etc.) plus iterate over any new services.
I do _not_ believe though that the existing macro can be extended well to support the pipe service definitions. While there is some duplication in the code, trying to template both service definitions with the same macro will make the macro needlessly complex I fear.

**Comment by javierbertoli** [comment]
Thanks for your explanation, makes sense, and I'm OK with keeping both cases separated as you wrote them.

I'll wait for your new commit, but so far, it LGTM :+1:

**Comment by aboe76** [comment]
@ixs thanks for your work

**Pull request merged**
