### PR TITLE
style: quote modes/numbers

### PR DESCRIPTION
**Pull request by jasonious**
salt-lint complains about these
```
[208] File modes should always contain a leading zero
22
/github/workspace/salt/formulas/postfix-formula/postfix/init.sls:46
23
    - mode: 644
```

### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [x] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

This should fix linter errors found by https://github.com/marketplace/actions/salt-lint 

### Describe the changes you're proposing

Properly writing and quoting file modes

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by fzipi** [comment]
Hi @jasonious ! Thanks for your patch! Can you prefix also with a `0`? (see https://github.com/warpnet/salt-lint/wiki/208)

**Review by fzipi — COMMENTED** [review]
According to https://github.com/warpnet/salt-lint/wiki/208, we should also prefix them with `0`.

**Comment by jasonious** [comment]
@fzipi yup, just took care of the leading zero but am failing commitlint right now.

**Comment by jasonious** [comment]
I think I've done things correctly now, but if there's anything I need to do, please let me know.

**Review by myii — APPROVED** [review]
This comment applies here as well:

* https://github.com/saltstack-formulas/users-formula/pull/222#issuecomment-702918061

**Comment by myii** [comment]
@jasonious Thanks again!

**Pull request merged**
