### PR TITLE
#29 postmap macro

### PR DESCRIPTION
**Pull request by EvaSDK**
Here is a proposal macro for dealing with files that need to be postmap'ed.
Beware that I have not been able to run it as I do not have a setup needing any of it yet.

### CODE REVIEW

**Comment by EvaSDK** [comment]
ping ?

**Comment by gravyboat** [comment]
Not sure how this one got missed @EvaSDK. I think that macro is going to cause problems for users on old Jinja releases, but I'll merge it for now. Thanks for the contribution.

**Comment by EvaSDK** [comment]
Not sure what could make it fail for older jinja, it's like the simplest macro I have seen for now. Refering to nginx for example :-) Anyway, thanks for the merge.

**Comment by gravyboat** [comment]
I think it's the use of the macros themselves, I believe they aren't supported in older jinja releases? Something isn't supported, I just never remember what it is.

**Pull request merged**
