### PR TITLE
Fix testing

### PR DESCRIPTION
**Pull request by javierbertoli**
Testing is failing in #74.

Add missing Gemfile, updated inspec verifier reporter format

### CODE REVIEW

**Comment by ixs** [comment]
It's an improvement but something is off.
From the CentOS target:

  ×  Postfix service: should be running (1 failed)
     ✔  Service postfix should be enabled
     ✔  Service postfix should be running
     ×  Port 25 should be listening
     expected `Port 25.listening?` to return true, got false
  ✔  Postfix packages: should be installed
     ✔  System Package postfix should be installed

**Comment by javierbertoli** [comment]
Yeah, saw that. Later today will try to see what's going on and fix it

**Comment by ixs** [comment]
Love to. But I do not think I have merge permissions here.

**Comment by javierbertoli** [comment]
@aboe76, @noelmcloughlin any of you could merge this, please?

**Pull request merged**
