### PR TITLE
fix(resources): modify names to match template-formula's

### LINKED ISSUE #119: [BUG] resources IDs are not unique and collide with other formulas
### Formula commit hash / release tag

Tested using commit 19617a0 (tag v1.2.2)

### Versions reports (master & minion)

```
# salt --versions-report
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: 0.27.7
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 0.27.4
        Python: 3.7.7 (default, Apr  1 2020, 13:48:52)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: debian testing bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-1-amd64
        system: Linux
       version: Debian GNU/Linux testing bullseye
```

### Pillar / config used

No config needed, just using the followin `top.sls`

```yaml
base:
  mail:
    - mysql.client
    - postfix
    - postfix.config
    - postfix.mysql
    - postfix.pcre
```

---

### Describe the bug

There are conflicting resource IDs between the `mysql.client` and `postfix.mysql` state files.

### Steps to reproduce the bug

```bash
~# salt 'mail' state.apply
ERROR: Minions returned with non-zero exit code
mail:
    Data failed to compile:
----------
    Detected conflicting IDs, SLS IDs need to be globally unique.
    The conflicting ID is 'mysql' and is found in SLS 'base:mysql.client' and SLS 'base:postfix.mysql'
```

### Expected behaviour

ID's should not conflict.

### Attempts to fix the bug

See PR #120

### PR DESCRIPTION
**Pull request by javierbertoli**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [X] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No, but will break dependencies to this formula resources's IDs being used in other formulas.

### Related issues and/or pull requests

Should fix #119

### Describe the changes you're proposing

Modified the resources IDs in the state files to follow the pattern proposed in the [template-formula](https://github.com/saltstack-formulas/template-formula/)

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [X] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by baby-gnu — CHANGES_REQUESTED** [review]
> ## Does this PR introduce a BREAKING CHANGE?
> No, but will break dependencies to this formula resources's IDs being used in other formulas.

I think this would be considered a BREAKING CHANGE to be sure users would notice the change and adapt their own SLS if required.

Thanks.

**Comment by javierbertoli** [comment]
@baby-gnu I agree, modified the message.

I just was not sure if external dependencies on this formula (while the formula's functionality remained the same), was a reason enough to mark it as a BREAKING CHANGE. 

But I noticed we did the same in the [template-formula](https://github.com/saltstack-formulas/template-formula/releases/tag/v4.0.0) so makes sense to mark it as such. :yum:

**Review by baby-gnu — APPROVED** [review]

**Comment by myii** [comment]
@javierbertoli The tests aren't running because `pre-commit` is failing (due to a `salt-lint` violation):

* https://gitlab.com/saltstack-formulas/postfix-formula/-/jobs/1098452788

Please amend the commit to fix that, so that the CI continues to work.

---

However, I've manually started all of the jobs and the good news is that they're passing:

* https://gitlab.com/saltstack-formulas/postfix-formula/-/pipelines/270561100

---

> @baby-gnu I agree, modified the message.

I agree with the `BREAKING CHANGE`, so thank you for adding that.  I've run a search for formulas which potentially may be affected by this change.  These are all of the formulas mentioning `postfix` that aren't in this formula itself:

* https://github.com/search?q=org%3Asaltstack-formulas+postfix+NOT+repo%3Asaltstack-formulas%2Fpostfix-formula&type=Code&ref=advsearch&l=&l=

It would be worth glancing over that list to see if there is anything obvious that would need to be fixed.

---

In terms of merging, we have a codeowner defined for this formula, so let's give @fzipi a chance to review this PR.

Thanks for finding the issue and supplying a prompt fix!

**Review by myii — CHANGES_REQUESTED** [review]
Just the `salt-lint` violation, AFAICT -- thanks.

**Comment by fzipi** [comment]
LGTM (other that fixing the lint problem). Do you think we should clarify somewhere the naming format used from now on?

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
@javierbertoli Merged.  Thanks for the reviews, @baby-gnu @fzipi.

> ... Do you think we should clarify somewhere the naming format used from now on?

@javierbertoli What do you think about this issue?  Cover it in another PR?

**Pull request merged**
