### PR TITLE
run postmap also for regexp maps

### PR DESCRIPTION
**Pull request by hoonetorg**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

Run postmap also for regexp style maps

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
Thanks for the PR, @hoonetorg.  Please see the [contributing guidelines](https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst#commit-message-formatting) for how to format commit messages for our formulas.  As an example, the new message may be something like:

```diff
-run postmap also for regexp maps
+feat(config): run postmap also for regexp maps
```

* Ideally, just amend the commit message and then force push back to the branch you've used for this PR.

Hopefully, @fzipi will be able to review and merge this PR after that.

**Comment by fzipi** [comment]
We should think about having tests for each different file type in the future.

**Comment by myii** [comment]
@fzipi Care to merge?  I prefer to leave it to code owners where we have those set!

**Comment by myii** [comment]
> We should think about having tests for each different file type in the future.

That's an excellent idea.

**Comment by hoonetorg** [comment]
Thx for quick merging.
I agree on writing more granular tests.
Keep up with the good work.

**Pull request merged**
