### PR TITLE
Added config files for virtual users

### PR DESCRIPTION
**Pull request by imran1008**

### CODE REVIEW

**Comment by gravyboat** [comment]
Good stuff, thanks.

**Comment by EvaSDK** [comment]
Sadly this work re-adds duplication that was removed in #43. I will now watch to repository to catch such errors but a deeper look before merging would have been nice.

**Comment by iggy** [comment]
This kind of stuff is going to happen when you have maintenance by team. It's unfortunate, but sending a revert is the most useful solution (that or joining the massively understaffed group of volunteers that maintains all 250ish formulas in their free time).

**Comment by gravyboat** [comment]
I've left a good number of PRs open for a while hoping people would comment (even mentioning people directly when it appears to apply to them) and the response rate is probably less than 10%. No one really cares until it breaks their setup.

**Pull request merged**
