### PR TITLE
Manage certificates from pillars

### PR DESCRIPTION
**Pull request by EvaSDK**
Same as PR#19 but with nginx.ng formula approach.

I left TLS random source modifications out since I believe there are better solutions like using haveged.

### CODE REVIEW

**Comment by gravyboat** [comment]
@iggy, @imran1008 comments or concerns? Looks like a good addition to me.

**Comment by puneetk** [comment]
Please rebase, cant merge it like this.

**Comment by imran1008** [comment]
Looks good to me too. Thanks

**Comment by EvaSDK** [comment]
Rebase done.

**Pull request merged**
