### PR TITLE
install postfix addons ( Debian Only)

### PR DESCRIPTION
**Pull request by danoe**
- mysql
  - pcre

### CODE REVIEW

**Comment by danoe** [comment]
To clearify, on CentOS and ArchLinux, these plugins are already in the base package of postfix.
On gentoo these are compiled via useflags, i don't know how i could implement this here.

**Comment by babilen** [comment]
Ta!

**Comment by opobla** [comment]
Hi. I was not able to call the postix.pcre state directly. I got:

```
$ salt-call state.sls postfix.pcre
[INFO    ] Loading fresh modules for state activity
local:
    Data failed to compile:
----------
    Cannot extend ID 'postfix' in 'base:postfix.pcre'. It is not part of the high state.
This is likely due to a missing include statement or an incorrectly typed ID.
Ensure that a state with an ID of 'postfix' is available
in environment 'base' and to SLS 'postfix.pcre'
```
So I did:

```
diff --git a/postfix/pcre.sls b/postfix/pcre.sls
index 1d104c0..28dffd0 100644
--- a/postfix/pcre.sls
+++ b/postfix/pcre.sls
@@ -1,4 +1,6 @@
 {% from "postfix/map.jinja" import postfix with context %}
+include:
+  - postfix
 
 pcre:
   pkg.installed:
```
And now I can `salt-call state.sls postfix.pcre` correctly. Am I using this incorrectly?

Thanks

**Comment by babilen** [comment]
@opobla Looks as if that include is indeed missing.

**Pull request merged**
