### PR TITLE
Ensure parameters don't get added if set to no

### PR DESCRIPTION
**Pull request by marhag87**

### CODE REVIEW

**Comment by EvaSDK** [comment]
Actually you should append all parameters under the positive branch of the test so they do not end up added by https://github.com/saltstack-formulas/postfix-formula/blob/master/postfix/files/main.cf#L113-L117

**Comment by ixs** [comment]
The PR is a possible solution to the problem but it is not ideal.

The base of the observed problem is actually somewhat different and either needs more rework of the set_parameter or a documentation note to make it more obvious.

When the pillar is loaded as yaml an implicit casting takes place. Values such as yes, no, false, False, true, True all get implicitly casted to the python boolean types True and False.

When these values are processed by the set_parameter macro, the _if value is number or value is string_ returns true and the parameter is written out as {{ parameter }} = {{ value }}.
And Value will be False due to the implicit casting. False is a parameter value though that is not understood by Postfix.

The PR works because the check for value == 'yes' would fail and thus having the value add to the processed_parameters list seems to work.

But the best solution is to quote 'yes' and 'no' values in the pillar as that prevents the implicit cast.
If a default parameter such as compatibility_level or smtpd_use_tls should not even make it into the generated file, leaving the value empty will work. The empty value is cast to None for which a check is available in the set_parameter macro.
It'll be run twice for these parameters but it's not going to result in any output...

**Comment by EvaSDK** [comment]
Note that this behavior is documented in https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html and a common pitfall of writing saltstack pillar data.

**Comment by ixs** [comment]
I'd suggest closing this PR. It's based on an incorrect understanding of yaml parsing and casting of values.

**Pull request closed without merging**
