### PR TITLE
refactor(maps): move tls_policy and transport maps to standard mapping

### PR DESCRIPTION
**Pull request by fzipi**
Signed-off-by: Felipe Zipitria <fzipitria@perceptyx.com>

Will push additional PRs with small fixes and.. tests :smile: 

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

YES.

Changing the `transport` will affect pillars defined in the original format. Now the map definition should be below the `mapping` key, as shown in the `pillar.example` file.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by fzipi** [comment]
@daks Please check this one and the other two I've sent.

**Comment by fzipi** [comment]
@myii Can you provide feedback?

**Comment by myii** [comment]
@fzipi Apologies, there are fewer people available for review these days.  We've spoken about this in the Formulas' Working Group meetings, to find the right ways to tackle this.  Have a look at our current sprint in Taiga to get an idea of what we've covered:

* https://tree.taiga.io/project/myii-saltstack-formulas/taskboard/meeting-004

Specifically, the tasks under the user story (left column):

> #224 Develop strategy for taking advantage of provided `CODEOWNERS` across formulas (e.g. decentralise formulas' maintenance): achieve better response times for issues and PRs, improve sustainability by delegating the maintenance burden, etc.

One of the main ideas is to use the `CODEOWNERS` file to help keep formulas well-maintained by encouraging regular contributors to take ownership of certain formulas, with our support of course.  So that means adding a global owner to this section:

https://github.com/saltstack-formulas/postfix-formula/blob/2f9c96e17078ced0fa80d9a4c245a107eaa727cd/CODEOWNERS#L3-L9

While explaining that many files in the formula will still be maintained by us (to reduce the burden):

https://github.com/saltstack-formulas/postfix-formula/blob/2f9c96e17078ced0fa80d9a4c245a107eaa727cd/CODEOWNERS#L14-L41

We've already got 40 formulas with a global code owner defined:

* https://github.com/saltstack-formulas/.github/blob/master/CONTRIBUTING.rst#semantic-release-formulas

So since you've shown a lot of interest in this formula and you've got PRs that you'd like to merge here, how would you feel about helping out with the maintenance of this formula?  That means you would have the ability to work with issues and PRs, including merging your own PRs if there is no feedback within a certain period of time.

**Comment by fzipi** [comment]
@myii Sure, count me in!

**Comment by myii** [comment]
> @myii Sure, count me in!

@fzipi Excellent, I've sent you an invite.  I'll add you to the `CODEOWNERS` file as well, as the global owner -- don't worry, we're all still here to give you a hand, so let us know if you need anything.

**Comment by myii** [comment]
@fzipi `CODEOWNERS` updated in f49290cc92eb5bbe2f70da17ccc633dc95f9d0fe -- welcome to the formula, you're in charge now!

Actually, since the CI is still using the old pre-salted images here, I'll send you through your first PR to consider for merging -- I'll do that soon so that your current PRs can benefit from that.

**Comment by myii** [comment]
OK, testing with the latest pre-salted images now:

* https://travis-ci.org/github/myii/postfix-formula/builds/695149799

**Comment by myii** [comment]
Nice, all working first time, so PR submitted: #110.

**Comment by fzipi** [comment]
After reviewing, this maybe has a breaking change for transport (small, but would break pillars for those who has it). Will add the breaking stanza to the commit.

**Pull request merged**
